name: CI/CD Backend Ventas

on:
  push:
    branches:
      - deploy
    paths:
      - 'back-Ventas_SpringBoot/Springboot-API-REST'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener el código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y Subir Imagen
        uses: docker/build-push-action@v4
        with:
          context: ./back-Ventas_SpringBoot/Springboot-API-REST
          file: ./back-Ventas_SpringBoot/Springboot-API-REST/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/back-ventas:latest

      - name: Desplegar en EC2 Privado (Vía Bastión)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PRIVATE_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          proxy_host: ${{ secrets.EC2_BASTION_HOST }}
          proxy_username: ec2-user
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/back-ventas:latest
            docker stop back-ventas || true
            docker rm back-ventas || true
            docker run -d -p 8081:8080 -e SPRING_DATASOURCE_URL="jdbc:mysql://${{ secrets.EC2_PRIVATE_HOST }}:3306/tienda_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true" -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=root --name back-ventas ${{ secrets.DOCKERHUB_USERNAME }}/back-ventas:latest